python dds_smpl.py loss=dds guidance_scale=10 epochs=50 prompt=A fat person front view name=dds_smpl_dds_10_50_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=50 prompt=A thin person front view name=dds_smpl_dds_10_50_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=50 prompt=A short person front view name=dds_smpl_dds_10_50_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=50 prompt=A tall person front view name=dds_smpl_dds_10_50_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=50 prompt=An Atheletic person front view name=dds_smpl_dds_10_50_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=100 prompt=A fat person front view name=dds_smpl_dds_10_100_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=100 prompt=A thin person front view name=dds_smpl_dds_10_100_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=100 prompt=A short person front view name=dds_smpl_dds_10_100_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=100 prompt=A tall person front view name=dds_smpl_dds_10_100_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=100 prompt=An Atheletic person front view name=dds_smpl_dds_10_100_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=200 prompt=A fat person front view name=dds_smpl_dds_10_200_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=200 prompt=A thin person front view name=dds_smpl_dds_10_200_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=200 prompt=A short person front view name=dds_smpl_dds_10_200_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=200 prompt=A tall person front view name=dds_smpl_dds_10_200_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=200 prompt=An Atheletic person front view name=dds_smpl_dds_10_200_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=300 prompt=A fat person front view name=dds_smpl_dds_10_300_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=300 prompt=A thin person front view name=dds_smpl_dds_10_300_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=300 prompt=A short person front view name=dds_smpl_dds_10_300_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=300 prompt=A tall person front view name=dds_smpl_dds_10_300_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=10 epochs=300 prompt=An Atheletic person front view name=dds_smpl_dds_10_300_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=50 prompt=A fat person front view name=dds_smpl_dds_20_50_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=50 prompt=A thin person front view name=dds_smpl_dds_20_50_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=50 prompt=A short person front view name=dds_smpl_dds_20_50_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=50 prompt=A tall person front view name=dds_smpl_dds_20_50_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=50 prompt=An Atheletic person front view name=dds_smpl_dds_20_50_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=100 prompt=A fat person front view name=dds_smpl_dds_20_100_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=100 prompt=A thin person front view name=dds_smpl_dds_20_100_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=100 prompt=A short person front view name=dds_smpl_dds_20_100_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=100 prompt=A tall person front view name=dds_smpl_dds_20_100_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=100 prompt=An Atheletic person front view name=dds_smpl_dds_20_100_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=200 prompt=A fat person front view name=dds_smpl_dds_20_200_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=200 prompt=A thin person front view name=dds_smpl_dds_20_200_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=200 prompt=A short person front view name=dds_smpl_dds_20_200_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=200 prompt=A tall person front view name=dds_smpl_dds_20_200_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=200 prompt=An Atheletic person front view name=dds_smpl_dds_20_200_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=300 prompt=A fat person front view name=dds_smpl_dds_20_300_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=300 prompt=A thin person front view name=dds_smpl_dds_20_300_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=300 prompt=A short person front view name=dds_smpl_dds_20_300_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=300 prompt=A tall person front view name=dds_smpl_dds_20_300_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=20 epochs=300 prompt=An Atheletic person front view name=dds_smpl_dds_20_300_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=50 prompt=A fat person front view name=dds_smpl_dds_30_50_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=50 prompt=A thin person front view name=dds_smpl_dds_30_50_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=50 prompt=A short person front view name=dds_smpl_dds_30_50_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=50 prompt=A tall person front view name=dds_smpl_dds_30_50_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=50 prompt=An Atheletic person front view name=dds_smpl_dds_30_50_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=100 prompt=A fat person front view name=dds_smpl_dds_30_100_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=100 prompt=A thin person front view name=dds_smpl_dds_30_100_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=100 prompt=A short person front view name=dds_smpl_dds_30_100_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=100 prompt=A tall person front view name=dds_smpl_dds_30_100_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=100 prompt=An Atheletic person front view name=dds_smpl_dds_30_100_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=200 prompt=A fat person front view name=dds_smpl_dds_30_200_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=200 prompt=A thin person front view name=dds_smpl_dds_30_200_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=200 prompt=A short person front view name=dds_smpl_dds_30_200_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=200 prompt=A tall person front view name=dds_smpl_dds_30_200_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=200 prompt=An Atheletic person front view name=dds_smpl_dds_30_200_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=300 prompt=A fat person front view name=dds_smpl_dds_30_300_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=300 prompt=A thin person front view name=dds_smpl_dds_30_300_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=300 prompt=A short person front view name=dds_smpl_dds_30_300_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=300 prompt=A tall person front view name=dds_smpl_dds_30_300_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=30 epochs=300 prompt=An Atheletic person front view name=dds_smpl_dds_30_300_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=50 prompt=A fat person front view name=dds_smpl_dds_40_50_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=50 prompt=A thin person front view name=dds_smpl_dds_40_50_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=50 prompt=A short person front view name=dds_smpl_dds_40_50_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=50 prompt=A tall person front view name=dds_smpl_dds_40_50_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=50 prompt=An Atheletic person front view name=dds_smpl_dds_40_50_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=100 prompt=A fat person front view name=dds_smpl_dds_40_100_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=100 prompt=A thin person front view name=dds_smpl_dds_40_100_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=100 prompt=A short person front view name=dds_smpl_dds_40_100_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=100 prompt=A tall person front view name=dds_smpl_dds_40_100_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=100 prompt=An Atheletic person front view name=dds_smpl_dds_40_100_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=200 prompt=A fat person front view name=dds_smpl_dds_40_200_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=200 prompt=A thin person front view name=dds_smpl_dds_40_200_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=200 prompt=A short person front view name=dds_smpl_dds_40_200_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=200 prompt=A tall person front view name=dds_smpl_dds_40_200_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=200 prompt=An Atheletic person front view name=dds_smpl_dds_40_200_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=300 prompt=A fat person front view name=dds_smpl_dds_40_300_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=300 prompt=A thin person front view name=dds_smpl_dds_40_300_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=300 prompt=A short person front view name=dds_smpl_dds_40_300_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=300 prompt=A tall person front view name=dds_smpl_dds_40_300_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=40 epochs=300 prompt=An Atheletic person front view name=dds_smpl_dds_40_300_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=50 prompt=A fat person front view name=dds_smpl_dds_50_50_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=50 prompt=A thin person front view name=dds_smpl_dds_50_50_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=50 prompt=A short person front view name=dds_smpl_dds_50_50_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=50 prompt=A tall person front view name=dds_smpl_dds_50_50_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=50 prompt=An Atheletic person front view name=dds_smpl_dds_50_50_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=100 prompt=A fat person front view name=dds_smpl_dds_50_100_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=100 prompt=A thin person front view name=dds_smpl_dds_50_100_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=100 prompt=A short person front view name=dds_smpl_dds_50_100_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=100 prompt=A tall person front view name=dds_smpl_dds_50_100_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=100 prompt=An Atheletic person front view name=dds_smpl_dds_50_100_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=200 prompt=A fat person front view name=dds_smpl_dds_50_200_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=200 prompt=A thin person front view name=dds_smpl_dds_50_200_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=200 prompt=A short person front view name=dds_smpl_dds_50_200_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=200 prompt=A tall person front view name=dds_smpl_dds_50_200_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=200 prompt=An Atheletic person front view name=dds_smpl_dds_50_200_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=300 prompt=A fat person front view name=dds_smpl_dds_50_300_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=300 prompt=A thin person front view name=dds_smpl_dds_50_300_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=300 prompt=A short person front view name=dds_smpl_dds_50_300_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=300 prompt=A tall person front view name=dds_smpl_dds_50_300_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=50 epochs=300 prompt=An Atheletic person front view name=dds_smpl_dds_50_300_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=50 prompt=A fat person front view name=dds_smpl_dds_100_50_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=50 prompt=A thin person front view name=dds_smpl_dds_100_50_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=50 prompt=A short person front view name=dds_smpl_dds_100_50_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=50 prompt=A tall person front view name=dds_smpl_dds_100_50_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=50 prompt=An Atheletic person front view name=dds_smpl_dds_100_50_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=100 prompt=A fat person front view name=dds_smpl_dds_100_100_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=100 prompt=A thin person front view name=dds_smpl_dds_100_100_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=100 prompt=A short person front view name=dds_smpl_dds_100_100_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=100 prompt=A tall person front view name=dds_smpl_dds_100_100_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=100 prompt=An Atheletic person front view name=dds_smpl_dds_100_100_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=200 prompt=A fat person front view name=dds_smpl_dds_100_200_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=200 prompt=A thin person front view name=dds_smpl_dds_100_200_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=200 prompt=A short person front view name=dds_smpl_dds_100_200_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=200 prompt=A tall person front view name=dds_smpl_dds_100_200_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=200 prompt=An Atheletic person front view name=dds_smpl_dds_100_200_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=300 prompt=A fat person front view name=dds_smpl_dds_100_300_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=300 prompt=A thin person front view name=dds_smpl_dds_100_300_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=300 prompt=A short person front view name=dds_smpl_dds_100_300_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=300 prompt=A tall person front view name=dds_smpl_dds_100_300_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=100 epochs=300 prompt=An Atheletic person front view name=dds_smpl_dds_100_300_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=50 prompt=A fat person front view name=dds_smpl_dds_150_50_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=50 prompt=A thin person front view name=dds_smpl_dds_150_50_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=50 prompt=A short person front view name=dds_smpl_dds_150_50_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=50 prompt=A tall person front view name=dds_smpl_dds_150_50_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=50 prompt=An Atheletic person front view name=dds_smpl_dds_150_50_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=100 prompt=A fat person front view name=dds_smpl_dds_150_100_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=100 prompt=A thin person front view name=dds_smpl_dds_150_100_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=100 prompt=A short person front view name=dds_smpl_dds_150_100_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=100 prompt=A tall person front view name=dds_smpl_dds_150_100_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=100 prompt=An Atheletic person front view name=dds_smpl_dds_150_100_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=200 prompt=A fat person front view name=dds_smpl_dds_150_200_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=200 prompt=A thin person front view name=dds_smpl_dds_150_200_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=200 prompt=A short person front view name=dds_smpl_dds_150_200_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=200 prompt=A tall person front view name=dds_smpl_dds_150_200_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=200 prompt=An Atheletic person front view name=dds_smpl_dds_150_200_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=300 prompt=A fat person front view name=dds_smpl_dds_150_300_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=300 prompt=A thin person front view name=dds_smpl_dds_150_300_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=300 prompt=A short person front view name=dds_smpl_dds_150_300_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=300 prompt=A tall person front view name=dds_smpl_dds_150_300_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=150 epochs=300 prompt=An Atheletic person front view name=dds_smpl_dds_150_300_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=50 prompt=A fat person front view name=dds_smpl_dds_200_50_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=50 prompt=A thin person front view name=dds_smpl_dds_200_50_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=50 prompt=A short person front view name=dds_smpl_dds_200_50_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=50 prompt=A tall person front view name=dds_smpl_dds_200_50_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=50 prompt=An Atheletic person front view name=dds_smpl_dds_200_50_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=100 prompt=A fat person front view name=dds_smpl_dds_200_100_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=100 prompt=A thin person front view name=dds_smpl_dds_200_100_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=100 prompt=A short person front view name=dds_smpl_dds_200_100_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=100 prompt=A tall person front view name=dds_smpl_dds_200_100_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=100 prompt=An Atheletic person front view name=dds_smpl_dds_200_100_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=200 prompt=A fat person front view name=dds_smpl_dds_200_200_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=200 prompt=A thin person front view name=dds_smpl_dds_200_200_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=200 prompt=A short person front view name=dds_smpl_dds_200_200_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=200 prompt=A tall person front view name=dds_smpl_dds_200_200_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=200 prompt=An Atheletic person front view name=dds_smpl_dds_200_200_An_Atheletic_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=300 prompt=A fat person front view name=dds_smpl_dds_200_300_A_fat_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=300 prompt=A thin person front view name=dds_smpl_dds_200_300_A_thin_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=300 prompt=A short person front view name=dds_smpl_dds_200_300_A_short_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=300 prompt=A tall person front view name=dds_smpl_dds_200_300_A_tall_person_front_view
python dds_smpl.py loss=dds guidance_scale=200 epochs=300 prompt=An Atheletic person front view name=dds_smpl_dds_200_300_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=50 prompt=A fat person front view name=dds_smpl_sds_10_50_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=50 prompt=A thin person front view name=dds_smpl_sds_10_50_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=50 prompt=A short person front view name=dds_smpl_sds_10_50_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=50 prompt=A tall person front view name=dds_smpl_sds_10_50_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=50 prompt=An Atheletic person front view name=dds_smpl_sds_10_50_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=100 prompt=A fat person front view name=dds_smpl_sds_10_100_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=100 prompt=A thin person front view name=dds_smpl_sds_10_100_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=100 prompt=A short person front view name=dds_smpl_sds_10_100_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=100 prompt=A tall person front view name=dds_smpl_sds_10_100_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=100 prompt=An Atheletic person front view name=dds_smpl_sds_10_100_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=200 prompt=A fat person front view name=dds_smpl_sds_10_200_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=200 prompt=A thin person front view name=dds_smpl_sds_10_200_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=200 prompt=A short person front view name=dds_smpl_sds_10_200_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=200 prompt=A tall person front view name=dds_smpl_sds_10_200_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=200 prompt=An Atheletic person front view name=dds_smpl_sds_10_200_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=300 prompt=A fat person front view name=dds_smpl_sds_10_300_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=300 prompt=A thin person front view name=dds_smpl_sds_10_300_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=300 prompt=A short person front view name=dds_smpl_sds_10_300_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=300 prompt=A tall person front view name=dds_smpl_sds_10_300_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=10 epochs=300 prompt=An Atheletic person front view name=dds_smpl_sds_10_300_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=50 prompt=A fat person front view name=dds_smpl_sds_20_50_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=50 prompt=A thin person front view name=dds_smpl_sds_20_50_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=50 prompt=A short person front view name=dds_smpl_sds_20_50_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=50 prompt=A tall person front view name=dds_smpl_sds_20_50_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=50 prompt=An Atheletic person front view name=dds_smpl_sds_20_50_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=100 prompt=A fat person front view name=dds_smpl_sds_20_100_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=100 prompt=A thin person front view name=dds_smpl_sds_20_100_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=100 prompt=A short person front view name=dds_smpl_sds_20_100_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=100 prompt=A tall person front view name=dds_smpl_sds_20_100_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=100 prompt=An Atheletic person front view name=dds_smpl_sds_20_100_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=200 prompt=A fat person front view name=dds_smpl_sds_20_200_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=200 prompt=A thin person front view name=dds_smpl_sds_20_200_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=200 prompt=A short person front view name=dds_smpl_sds_20_200_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=200 prompt=A tall person front view name=dds_smpl_sds_20_200_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=200 prompt=An Atheletic person front view name=dds_smpl_sds_20_200_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=300 prompt=A fat person front view name=dds_smpl_sds_20_300_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=300 prompt=A thin person front view name=dds_smpl_sds_20_300_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=300 prompt=A short person front view name=dds_smpl_sds_20_300_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=300 prompt=A tall person front view name=dds_smpl_sds_20_300_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=20 epochs=300 prompt=An Atheletic person front view name=dds_smpl_sds_20_300_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=50 prompt=A fat person front view name=dds_smpl_sds_30_50_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=50 prompt=A thin person front view name=dds_smpl_sds_30_50_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=50 prompt=A short person front view name=dds_smpl_sds_30_50_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=50 prompt=A tall person front view name=dds_smpl_sds_30_50_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=50 prompt=An Atheletic person front view name=dds_smpl_sds_30_50_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=100 prompt=A fat person front view name=dds_smpl_sds_30_100_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=100 prompt=A thin person front view name=dds_smpl_sds_30_100_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=100 prompt=A short person front view name=dds_smpl_sds_30_100_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=100 prompt=A tall person front view name=dds_smpl_sds_30_100_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=100 prompt=An Atheletic person front view name=dds_smpl_sds_30_100_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=200 prompt=A fat person front view name=dds_smpl_sds_30_200_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=200 prompt=A thin person front view name=dds_smpl_sds_30_200_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=200 prompt=A short person front view name=dds_smpl_sds_30_200_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=200 prompt=A tall person front view name=dds_smpl_sds_30_200_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=200 prompt=An Atheletic person front view name=dds_smpl_sds_30_200_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=300 prompt=A fat person front view name=dds_smpl_sds_30_300_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=300 prompt=A thin person front view name=dds_smpl_sds_30_300_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=300 prompt=A short person front view name=dds_smpl_sds_30_300_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=300 prompt=A tall person front view name=dds_smpl_sds_30_300_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=30 epochs=300 prompt=An Atheletic person front view name=dds_smpl_sds_30_300_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=50 prompt=A fat person front view name=dds_smpl_sds_40_50_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=50 prompt=A thin person front view name=dds_smpl_sds_40_50_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=50 prompt=A short person front view name=dds_smpl_sds_40_50_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=50 prompt=A tall person front view name=dds_smpl_sds_40_50_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=50 prompt=An Atheletic person front view name=dds_smpl_sds_40_50_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=100 prompt=A fat person front view name=dds_smpl_sds_40_100_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=100 prompt=A thin person front view name=dds_smpl_sds_40_100_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=100 prompt=A short person front view name=dds_smpl_sds_40_100_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=100 prompt=A tall person front view name=dds_smpl_sds_40_100_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=100 prompt=An Atheletic person front view name=dds_smpl_sds_40_100_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=200 prompt=A fat person front view name=dds_smpl_sds_40_200_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=200 prompt=A thin person front view name=dds_smpl_sds_40_200_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=200 prompt=A short person front view name=dds_smpl_sds_40_200_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=200 prompt=A tall person front view name=dds_smpl_sds_40_200_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=200 prompt=An Atheletic person front view name=dds_smpl_sds_40_200_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=300 prompt=A fat person front view name=dds_smpl_sds_40_300_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=300 prompt=A thin person front view name=dds_smpl_sds_40_300_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=300 prompt=A short person front view name=dds_smpl_sds_40_300_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=300 prompt=A tall person front view name=dds_smpl_sds_40_300_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=40 epochs=300 prompt=An Atheletic person front view name=dds_smpl_sds_40_300_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=50 prompt=A fat person front view name=dds_smpl_sds_50_50_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=50 prompt=A thin person front view name=dds_smpl_sds_50_50_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=50 prompt=A short person front view name=dds_smpl_sds_50_50_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=50 prompt=A tall person front view name=dds_smpl_sds_50_50_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=50 prompt=An Atheletic person front view name=dds_smpl_sds_50_50_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=100 prompt=A fat person front view name=dds_smpl_sds_50_100_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=100 prompt=A thin person front view name=dds_smpl_sds_50_100_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=100 prompt=A short person front view name=dds_smpl_sds_50_100_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=100 prompt=A tall person front view name=dds_smpl_sds_50_100_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=100 prompt=An Atheletic person front view name=dds_smpl_sds_50_100_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=200 prompt=A fat person front view name=dds_smpl_sds_50_200_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=200 prompt=A thin person front view name=dds_smpl_sds_50_200_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=200 prompt=A short person front view name=dds_smpl_sds_50_200_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=200 prompt=A tall person front view name=dds_smpl_sds_50_200_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=200 prompt=An Atheletic person front view name=dds_smpl_sds_50_200_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=300 prompt=A fat person front view name=dds_smpl_sds_50_300_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=300 prompt=A thin person front view name=dds_smpl_sds_50_300_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=300 prompt=A short person front view name=dds_smpl_sds_50_300_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=300 prompt=A tall person front view name=dds_smpl_sds_50_300_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=50 epochs=300 prompt=An Atheletic person front view name=dds_smpl_sds_50_300_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=50 prompt=A fat person front view name=dds_smpl_sds_100_50_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=50 prompt=A thin person front view name=dds_smpl_sds_100_50_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=50 prompt=A short person front view name=dds_smpl_sds_100_50_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=50 prompt=A tall person front view name=dds_smpl_sds_100_50_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=50 prompt=An Atheletic person front view name=dds_smpl_sds_100_50_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=100 prompt=A fat person front view name=dds_smpl_sds_100_100_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=100 prompt=A thin person front view name=dds_smpl_sds_100_100_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=100 prompt=A short person front view name=dds_smpl_sds_100_100_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=100 prompt=A tall person front view name=dds_smpl_sds_100_100_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=100 prompt=An Atheletic person front view name=dds_smpl_sds_100_100_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=200 prompt=A fat person front view name=dds_smpl_sds_100_200_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=200 prompt=A thin person front view name=dds_smpl_sds_100_200_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=200 prompt=A short person front view name=dds_smpl_sds_100_200_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=200 prompt=A tall person front view name=dds_smpl_sds_100_200_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=200 prompt=An Atheletic person front view name=dds_smpl_sds_100_200_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=300 prompt=A fat person front view name=dds_smpl_sds_100_300_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=300 prompt=A thin person front view name=dds_smpl_sds_100_300_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=300 prompt=A short person front view name=dds_smpl_sds_100_300_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=300 prompt=A tall person front view name=dds_smpl_sds_100_300_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=100 epochs=300 prompt=An Atheletic person front view name=dds_smpl_sds_100_300_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=50 prompt=A fat person front view name=dds_smpl_sds_150_50_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=50 prompt=A thin person front view name=dds_smpl_sds_150_50_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=50 prompt=A short person front view name=dds_smpl_sds_150_50_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=50 prompt=A tall person front view name=dds_smpl_sds_150_50_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=50 prompt=An Atheletic person front view name=dds_smpl_sds_150_50_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=100 prompt=A fat person front view name=dds_smpl_sds_150_100_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=100 prompt=A thin person front view name=dds_smpl_sds_150_100_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=100 prompt=A short person front view name=dds_smpl_sds_150_100_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=100 prompt=A tall person front view name=dds_smpl_sds_150_100_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=100 prompt=An Atheletic person front view name=dds_smpl_sds_150_100_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=200 prompt=A fat person front view name=dds_smpl_sds_150_200_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=200 prompt=A thin person front view name=dds_smpl_sds_150_200_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=200 prompt=A short person front view name=dds_smpl_sds_150_200_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=200 prompt=A tall person front view name=dds_smpl_sds_150_200_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=200 prompt=An Atheletic person front view name=dds_smpl_sds_150_200_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=300 prompt=A fat person front view name=dds_smpl_sds_150_300_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=300 prompt=A thin person front view name=dds_smpl_sds_150_300_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=300 prompt=A short person front view name=dds_smpl_sds_150_300_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=300 prompt=A tall person front view name=dds_smpl_sds_150_300_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=150 epochs=300 prompt=An Atheletic person front view name=dds_smpl_sds_150_300_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=50 prompt=A fat person front view name=dds_smpl_sds_200_50_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=50 prompt=A thin person front view name=dds_smpl_sds_200_50_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=50 prompt=A short person front view name=dds_smpl_sds_200_50_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=50 prompt=A tall person front view name=dds_smpl_sds_200_50_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=50 prompt=An Atheletic person front view name=dds_smpl_sds_200_50_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=100 prompt=A fat person front view name=dds_smpl_sds_200_100_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=100 prompt=A thin person front view name=dds_smpl_sds_200_100_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=100 prompt=A short person front view name=dds_smpl_sds_200_100_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=100 prompt=A tall person front view name=dds_smpl_sds_200_100_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=100 prompt=An Atheletic person front view name=dds_smpl_sds_200_100_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=200 prompt=A fat person front view name=dds_smpl_sds_200_200_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=200 prompt=A thin person front view name=dds_smpl_sds_200_200_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=200 prompt=A short person front view name=dds_smpl_sds_200_200_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=200 prompt=A tall person front view name=dds_smpl_sds_200_200_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=200 prompt=An Atheletic person front view name=dds_smpl_sds_200_200_An_Atheletic_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=300 prompt=A fat person front view name=dds_smpl_sds_200_300_A_fat_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=300 prompt=A thin person front view name=dds_smpl_sds_200_300_A_thin_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=300 prompt=A short person front view name=dds_smpl_sds_200_300_A_short_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=300 prompt=A tall person front view name=dds_smpl_sds_200_300_A_tall_person_front_view
python dds_smpl.py loss=sds guidance_scale=200 epochs=300 prompt=An Atheletic person front view name=dds_smpl_sds_200_300_An_Atheletic_person_front_view
Total number of jobs: 320
